manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: slicemk-module
      url-base: git@github.com:u-mikhalenka/ergodox-zmk-config.git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: slicemk-module
      remote: slicemk-module
      repo-path: slicemk-module
      revision: module
  self:
    path: config